security:
  enable_authenticator_manager: true
  encoders:
    App\User\Entity\User:
      algorithm: auto

  providers:
    users:
      entity:
        class: 'App\User\Entity\User'
        # the property to query by - e.g. username, email, etc
        property: 'email'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      custom_authenticators:
        - App\User\Security\ApiAuthenticator

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: ROLE_USER }
