controllers_helpdesk:
    resource: ../../src/Helpdesk/UI/Controller/
    type: annotation

controllers_user:
    resource: ../../src/User/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
