helpdesk_issue_controller:
  resource: ../../src/Helpdesk/UI/Controller/
  type: annotation

client_controller:
  resource: ../../src/Client/UI/Controller/
  type: annotation

dictionary_controllers:
  resource: ../../src/Dictionary/Controller/
  type: annotation

user_controllers:
  resource: ../../src/User/Controller/
  type: annotation



kernel:
  resource: ../../src/Kernel.php
  type: annotation
